### ISSUE TITLE
当activity调用requestWindowFeature(Window.FEATURE_NO_TITLE);时崩溃

### ISSUE THREAD

**Issue by caik13** [Sunzxyong/Recovery#1]
当activity里面调用requestWindowFeature(Window.FEATURE_NO_TITLE);这个的时候就会导致崩溃

**Comment by Sunzxyong** [comment]
Please call “requestWindowFeature(Window.FEATURE_NO_TITLE) or getWindow().requestFeature()” method before super.onCreate()

**Comment by caik13** [comment]
thanks.
