### ISSUE TITLE
异常日志的保存路径在哪里？

### ISSUE THREAD

**Issue by ChenQingZhen** [Sunzxyong/Recovery#24]
异常日志的保存路径在哪里？

**Comment by Sunzxyong** [comment]
@ChenQingZhen  {SDCard Dir}/Android/data/{packageName}/files/recovery_crash/

**Comment by ChenQingZhen** [comment]
这是应用内的私有路径，没有root权限是访问不了的

**Comment by Sunzxyong** [comment]
@ChenQingZhen 是保存在sd卡

**Comment by tangchao0106** [comment]
这个能不能设置崩溃之后,自动保存日志到本地文件夹,并且目录是可以自己设置的啊????

**Comment by Sunzxyong** [comment]
@tangchao0106 下一版会加上这个功能

**Comment by tangchao0106** [comment]
也不用了啊，配合logger使用，报错了会出现在logger日志里面的
