### ISSUE TITLE
ReadMe的问题

### ISSUE THREAD

**Issue by tvvbbb** [Sunzxyong/Recovery#32]
在英文版上：RESTART_AND_CLEAR - Restart App and clear data
在中文版上：重启应用并清空缓存数据
如果是清空缓存的话，英文应该是用cache吧？这个好像有点古怪

在英文版上静默模式的说明代码里面，silent是true的，但在中文文档里面却写成了false，这个是不是写错了？
在函数的说明文档上，并没有说明skip函数的作用，只有在更新日志里面说明了这个函数的作用。
RecoveryCallBack的函数说明用法，而且throwable不是包含了大部分信息，为什么还要分开这么多个函数？

**Comment by Sunzxyong** [comment]
@tvvbbb 嗯，对，是写错了，感谢反馈。

**Comment by tvvbbb** [comment]
好的
